server:
  port: 8091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/plazoleta
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: update
  
  security:
    user:
      name: root
      password: s3cr3t
    

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka

