server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://plazoleta.c7dvd1iqtniq.us-east-1.rds.amazonaws.com:3306/usuarios
    username: admin
    password: hola123456

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka

