server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/plazoleta
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka

